export const MESSAGE_TYPES = Object.freeze({
  DRAW_START: 'DRAW_START',
  DRAW_MOVE: 'DRAW_MOVE',
  DRAW_END: 'DRAW_END',
  CLEAR: 'CLEAR',
  CURSOR_MOVE: 'CURSOR_MOVE',
  UNDO: 'UNDO',
  REDO: 'REDO',
  STATE_SYNC: 'STATE_SYNC',
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  ERROR: 'ERROR',
});

export const COLOR_POOL = [
  '#FF5733',
  '#FFC300',
  '#2ECC71',
  '#3498DB',
  '#9B59B6',
  '#E67E22',
  '#E74C3C',
  '#1ABC9C',
  '#F1C40F',
  '#34495E',
];

export const MAX_OPERATIONS = 5000;
export const MAX_COORDINATE = 10000;
export const MIN_COORDINATE = -100;
